# Generated by Django 3.1.1 on 2021-06-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210620_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='zipcode',
        ),
    ]
